config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :items do
    resources :bookings, only: [:create, :new, :show]
  end

  get 'pages/thankyou', to: 'pages#thankyou'
  get 'pages/account', to: 'pages#account'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :item
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :user_id, presence: true
  validates :item_id, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :size, presence: true
  validates :gender, presence: true
  validates :available, presence: true
  validates :price, presence: true,
            numericality: {greater_than_or_equal_to: 0}
  validates :initial_condition, presence: true
  validates :brand, presence: true
  validates :num_uses, presence: true,
            numericality: {greater_than_or_equal_to: 0, only_integer: true}
  validates :available, inclusion: { in: [true, false] }

  has_one_attached :photo
  has_many :bookings
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items
  validates :email, presence: true, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(strong_params)
    @item = Item.find(params[:item_id])
    @booking.item = @item
    @booking.user = current_user

    if @booking.valid?
      @booking.save
      redirect_to pages_account_path
    end
  end

  def strong_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

   before_action :set_item, only: [:show, :edit, :update, :destroy]
   skip_before_action :authenticate_user!, only: [:index, :show]

  # GET /items
  def index
    @items = Item.all
  end

  # GET /items/1
  def show
    @item_id = params[:id]
    @booking = Booking.new
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = Item.new(item_params)
    @item.brand = @item.brand.downcase
    @item.item_type = @item.item_type.downcase
    @item.size = @item.size.downcase
    @item.gender = @item.gender.downcase
    @item.initial_condition = @item.initial_condition.downcase
    @item.available = true
    @item.user = current_user
     if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:name, :item_type, :size, :gender, :price, :brand, :initial_condition, :photo)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def thankyou
  end

  def account
    @bookings = current_user.bookings
    @items = current_user.items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
index.html.erb

app/views/bookings/new.html.erb
<div class="container">
  <div class="row p-5">
  <div class="col-5">
    <h1 class="text-left">Its Almost Yours!</h1>
    <%= cl_image_tag @item.photo.key, height: 450 %>
    </div>
    <div class="col-7 d-flex flex-column justify-content-center">
      <%= simple_form_for [@item, @booking] do |f| %>
        <%= f.input :start_date, as: :date, order: [:day, :month, :year], label: "I want it from..." %> 
        <%= f.input :end_date, as: :date, order: [:day, :month, :year], label: "Until..."%>
        <%= f.button :submit, "Rent it now!", class: "btn btn-primary ml-1"%>
      <% end %>
    </div>
  </div>
</div>

app/views/items/_banner.html.erb
 <div class="hero-img">
  <%= image_tag("VelvetBanner.jpg", :border=>0, :class => 'top')%>
  <%= image_tag("SmartDress.jpg", :border=>0, :class => 'middle')%>
  <%= image_tag("BlackTieBanner.jpg", :border=>0, :class => 'bottom')%>
    <div class="hero-text">
      <h1 class="mb-4">DressCode</h1>
      <%# <p>A LUMS Project blah blah whatever</p> %>
      <a id="landing-button">Find your Cinderella Moment</a>
    </div>
  </div>

app/views/items/_footer.html.erb
  <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Do not hesitate to follow us <i class="fas fa-heart"></i>
  </div>
</div>

app/views/items/index.html.erb
<%= render partial: "banner" %>

<div class="container" id="items">
  <h1 class="text-center mt-4 pt-4">Find your Cinderella Moment</h1>
  <hr>
  <div class="d-flex justify-content-center" id="filters">
      <!-- Gender menu -->
      <div class="dropdown">
        <div class="filter-dropdown dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Gender
        </div>
        <!-- Type Menu -->
        <div class="dropdown-menu pl-3 pb-0" aria-labelledby="dropdownMenuButton">
          <% item_gender_array = [] %>
            <% @items.each do |item| %>
              <% item_gender_array << item.gender %>
            <% end %>
            <% item_gender_array = item_gender_array.uniq %>
            <% item_gender_array.each do |i| %>
              <div class="checkbox">
                <label>
                  <input type="checkbox" name="gender" value="<%= i %>">
                  <%= i.capitalize %>
                </label>
              </div>
            <% end %>
        </div>
      </div>
      <div class="dropdown">
        <div class="filter-dropdown dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Type
        </div>
        <!-- Type Menu -->
        <div class="dropdown-menu pl-3 pb-0" aria-labelledby="dropdownMenuButton">
          <% item_type_array = [] %>
            <% @items.each do |item| %>
              <% item_type_array << item.item_type %>
            <% end %>
            <% item_type_array = item_type_array.uniq %>
            <% item_type_array.each do |i| %>
              <div class="checkbox">
                <label>
                  <input type="checkbox" name="item_type" value="<%= i %>">
                  <%= i.capitalize %>
                </label>
              </div>
            <% end %>
        </div>
      </div>
      <!-- Brand Menu -->
      <div class="dropdown">
        <div class="filter-dropdown dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Brand
        </div>
        <div class="dropdown-menu pl-3 pb-0" aria-labelledby="dropdownMenuButton">
          <% item_brand_array = [] %>
          <% @items.each do |item| %>
            <% item_brand_array << item.brand %>
          <% end %>
          <% item_brand_array = item_brand_array.uniq %>
          <% item_brand_array.each do |i| %>
            <div class="checkbox">
              <label>
                <input type="checkbox" name="brand" value="<%= i %>">
                <%= i.capitalize %>
              </label>
            </div>
          <% end %>
        </div>
      </div>
      <!-- Size Dropdown -->
      <div class="dropdown">
        <div class="filter-dropdown dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Size
        </div>
        <div class="dropdown-menu pl-3 pb-0" aria-labelledby="dropdownMenuButton">
          <% item_size_array = [] %>
          <% @items.each do |item| %>
            <% item_size_array << item.size %>
          <% end %>
          <% item_size_array = item_size_array.uniq %>
          <% item_size_array.each do |i| %>
            <div class="checkbox">
              <label>
                <input type="checkbox" name="size" value=<%= i %>>
                <%= i %>
              </label>
            </div>
          <% end %>
        </div>
      </div>
  </div>
  <div class="item-grid">
    <% @items.each do |item| %>
      <%= link_to item_path(item) do %>
          <div class="card-category item-card" data-gender="<%= item.gender %>" data-item_type="<%= item.item_type %>" data-brand ="<%= item.brand %>" data-size="<%= item.size %>" style="background-image: url('<%= item.photo.attached? ? (cl_image_path item.photo.key) : (image_path("defaultdress.jpg")) %>'), linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">
            <div class="item-description py-2">
              <h2><%= item.name %></h2>
               <p class="brand"><%= item.brand.capitalize %></p>
            </div>
          </div>
      <% end %>
    <% end %>
  </div>
</div>

<%= render partial: "footer" %>

app/views/items/new.html.erb
<%#= render 'form', item: @item %>
<div class="container">
<h2>Want To List an Item? Rent Yours Now!</h2>
<%= simple_form_for(@item) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= f.input :name %>
      </div>
      <div class="form-group col-md-6">
        <%= f.input :brand, as: :select, collection: ["Gucci", "Armani", "Dior", "Zara", "Rolex"] %>
      </div>
    </div>
    <div class="form-inputs">
    <div class="form-row">
      <div class="form-group col-md-6">
    <%= f.input :item_type , as: :select, collection: ["Dress", "Tuxedo", "Suit", "Shoes", "Watch"] %>
  </div>
  <div class="form-group col-md-6">
    <%= f.input :size, as: :select, collection: ["XL", "S", "M", "L", "XL"] %>
  </div>
</div>

  <div class="form-inputs">
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= f.input :gender, as: :select, collection: ["Male", "Female", "Unisex"] %>
      </div>
      <div class="form-group col-md-6">
        <%= f.input :initial_condition, as: :select, collection: ["New with tags", "Like new", "Contains defaults"] %>
      </div>
    </div>
    <div class="form-group col-md-4 p-0">
      <%= f.input :price %>
      <%= f.input :photo, as: :file %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, "Real Submit Button!", class: "btn btn-outline-dark", id: "RealItemSubmitButton", style: "display: none;" %>
      <a id="FakeItemSubmitButton" class="btn btn-outline-dark">Create Item!</a>
    </div>
  </div>
<% end %>

app/views/items/show.html.erb
<div class="container">
  <section>


 <div class="card-product mt-4">
<div class="item-img" style="background-image: url(<%= @item.photo.attached? ? (cl_image_path @item.photo.key) : (image_path("defaultdress.jpg")) %>); background-size: cover; background-position: center; linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))"></div>
  <div class="card-product-infos">
    <h2> <%= @item.name %> by <%= @item.brand %></h2>
    <p><%= @item.size %></p>
    <p><%= @item.initial_condition %></p>
    <p>Number of uses : <%= @item.num_uses %></p>
    <br>

    <%= simple_form_for [@item, @booking], method: :post do |f| %>
    <div class="row">
      <div class="col">
        <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
    </div>
      <div class="col">
        <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
    </div>
  </div>
   <br>
    <%= f.button :submit, "Book item", class: "btn btn-dark", id: "RealBookingSubmitButton", style: "display: none;" %>
    <a id="FakeBookingSubmitButton" class="btn btn-dark">Book item</a>
    <% end %>
    <p style="padding-left: 520px;font-size: 25px;"> <strong>£<%= @item.price %></strong></p>

  </div>
</div>


  </section>

  <section class="mt-5">
  <h3>Details</h3>
  <hr>
  </section>

  <section>
    <h3>Size and Fit</h3>
    <hr>
  </section>

  <section>
    <h3>Delivery and Returns</h3>
    <hr>
  </section>
</div>

<!-- <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAirbnbClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
      <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/account.html.erb
<h1>My Account Page</h1>

<div class="container">
  <section>
    <h1 class="text-center mt-4 pt-4">My Rented Items</h1>
<% @items.each do |item| %>
 <div class="card-product mt-4">
<!-- <div class="card-category item-card item-img" style="background-image: url(<%#= item.photo.attached? ? (cl_image_path item.photo.key) : (image_path("defaultdress.jpg")) %>), width: 200px; background-position: center; background-size: cover;"></div> -->
  <div class="item-img" style="background-image: url(<%= item.photo.attached? ? (cl_image_path item.photo.key) : (image_path("defaultdress.jpg")) %>); background-size: cover; background-position: center; linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))"></div>
  <div class="card-product-infos">
    <h2> <%= item.name %> by <%= item.brand %></h2>
    <p><%= item.size %></p>
    <p><%= item.initial_condition %></p>
    <p><%= item.num_uses %></p>
    <% item.bookings.each do |booking| %>
      <p><%= booking.user.email %></p>
      <p><%= booking.start_date %></p>
      <p><%= booking.end_date %></p>
    <% end %>
    <br>

    <p style="padding-left: 520px;font-size: 25px;"> <strong>£<%= item.price %></strong></p>

  </div>
</div>
</div>
<% end %>
</section>

<div class="container">
</section>
<h1 class="text-center mt-4 pt-4">My Bookings</h1>
<section>
  <% @bookings.each do |booking| %>
 <div class="card-product mt-4">
<!-- <div class="card-category item-card item-img" style="background-image: url(<%#= booking.item.photo.attached? ? (cl_image_path booking.item.photo.key) : (image_path("defaultdress.jpg")) %>), width: 200px; linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))"></div> -->
  <div class="item-img" style="background-image: url(<%= booking.item.photo.attached? ? (cl_image_path booking.item.photo.key) : (image_path("defaultdress.jpg")) %>); background-size: cover; background-position: center; linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))"></div>
  <div class="card-product-infos">
    <h2> <%= booking.item.name %> by <%= booking.item.brand %></h2>
    <p><%= booking.item.size %></p>
    <p><%= booking.item.initial_condition %></p>
    <p><%= booking.item.num_uses %></p>
    <br>

    <p style="padding-left: 520px;font-size: 25px;"> <strong>£<%= booking.item.price %></strong></p>

  </div>
<!-- </div> -->
<!-- </div> -->
</div>
<% end %>
</section>
</div>



</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/thankyou.html.erb
<div class="row h-100 flex-column justify-content-center align-items-center">
  <h1 class="text-center">Thank you for your booking!</h1>
  <img width="400px" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0f7xZrCI81eqJ3awywFgwwwL0TMnj2bQLlQ&usqp=CAU" alt="">
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_landing.html.erb
 <div class="hero-img">
    <div class="hero-text">
      <h1>DressCode</h1>
      <%# <p>A LUMS Project blah blah whatever</p> %>
      <a id="landing-button" href="#items">Find your Cinderella moment</a>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to items_path, class: "navbar-brand" do %>
    <%= image_tag("dresscodelogo-transparent.png") %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", items_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Post an Item", new_item_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><%=current_user.email%></a>
          <div class="dropdown-menu">
            <%= link_to 'My Account', pages_account_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
    </form> -->
      <% end %>
    </ul>
  </div>
</div>